#! /usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Telnet\Parser\AnsiAsciiControlParser;

$parser = new AnsiAsciiControlParser();

$f = fopen('php://stdin', 'r');

$parser = new AnsiAsciiControlParser();
while (false !== ($s = fgets($f))) {
    $parser->parse($s);
    print($parser->getTextString());
}

fclose($f);

?>
